### ISSUE TITLE
MongoError: E11000 duplicate key error collection: userDB.users index: username_1 dup key: { username: null }  

### ISSUE THREAD

**Issue by doongzzi** [londonappbrewery/Authentication-Secrets#1]
I added a facebook login button and it works perfectly fine. Problem is that, in the mongoDB facebook/google accounts generates DB without username. So if you register with google account and next you try to register with a different google/facebook account they both have a username:NULL which generates an error.
"MongoError: E11000 duplicate key error collection: userDB.users index: username_1 dup key: { username: null }"
how can i fix this???!

**Comment by Ashutosh1109** [comment]
> I added a facebook login button and it works perfectly fine. Problem is that, in the mongoDB facebook/google accounts generates DB without username. So if you register with google account and next you try to register with a different google/facebook account they both have a username:NULL which generates an error.
> "MongoError: E11000 duplicate key error collection: userDB.users index: username_1 dup key: { username: null }"
> how can i fix this???!

hey i also got same error,

**Comment by DavidNovillo** [comment]
I got the same error and is because the database doesn't allow two documents with the username = null (I've already signed in with google), so you need to fill the username field in the database. For the sign in with facebook option I did this:

passport.use(
  new FacebookStrategy(
    {
      clientID: process.env.FACEBOOK_APP_ID,
      clientSecret: process.env.FACEBOOK_APP_SECRET,
      callbackURL: "http://localhost:3000/auth/facebook/secrets",
      profileFields: ['id', 'displayName', 'email']
    },
    function (accessToken, refreshToken, profile, cb) {
      console.log(profile.emails[0].value);
      User.findOrCreate({ facebookId: profile.id, username: profile.emails[0].value }, function (err, user) {
        return cb(err, user);
      });
    }
  )
);

_profileFields: ['id', 'displayName', 'email']_ This part asks the user for permission to get the email from the facebook account, and saves it in the _profile_ object as an array of emails, then in this part _User.findOrCreate({ facebookId: profile.id, username: profile.emails[0].value }, function (err, user)_ you just find or create a new database document with the facebook id and the user's facebook email as the username, so you won't get the username field as null in your database.

**Comment by ayandagatsha** [comment]
Hi, I'm not even at the facebook part, i just added the code below and got the error. I don't know whats going on and why and it isn't discussed in the video. I've deleted my db and started again and still the same thing. Please help

CODE:
passport.serializeUser(function(user, done) {
  done(null, user.id);
});

passport.deserializeUser(function(id, done) {
  User.findById(id, function(err, user) {
    done(err, user);
  });
});


ERROR:


MongoError: E11000 duplicate key error collection: userDB.users 
index: username_1 dup key: { username: null }
    at Function.create (C:\Users\user\Desktop\angelas web dev 2021\webdev\backend\Secrets\node_modules\mongodb\lib\core\error.js:57:12)
    at toError (C:\Users\user\Desktop\angelas web dev 2021\webdev\backend\Secrets\node_modules\mongodb\lib\utils.js:123:22)
    at C:\Users\user\Desktop\angelas web dev 2021\webdev\backend\Secrets\node_modules\mongodb\lib\operations\common_functions.js:258:39
    at C:\Users\user\Desktop\angelas web dev 2021\webdev\backend\Secrets\node_modules\mongodb\lib\core\connection\pool.js:405:18    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by jarvisvsedith** [comment]
> I added a facebook login button and it works perfectly fine. Problem is that, in the mongoDB facebook/google accounts generates DB without username. So if you register with google account and next you try to register with a different google/facebook account they both have a username:NULL which generates an error.
> "MongoError: E11000 duplicate key error collection: userDB.users index: username_1 dup key: { username: null }"
> how can i fix this???!

I also have the same error I didn't even have Username Feild in my schema. I didn't use username field in both my google sign and normal registration.
