### ISSUE TITLE
 OAuth2Strategy requires a clientID option

### ISSUE THREAD

**Issue by pandeyom331** [londonappbrewery/Authentication-Secrets#16]
C:\Users\lenovo\Downloads\Authentication-Secrets-master\node_modules\passport-oauth2\lib\strategy.js:82   if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }                            
   ^  
TypeError: OAuth2Strategy requires a clientID option
        at Strategy.OAuth2Strategy (C:\Users\lenovo\Downloads\Authentication-Secrets-master\node_modules\passport-oauth2\lib\strategy.js:82:34)     
       at new Strategy (C:\Users\lenovo\Downloads\Authentication-Secrets-master\node_modules\passport-google-oauth20\lib\strategy.js:52:18)
       at Object.<anonymous> (C:\Users\lenovo\Downloads\Authentication-Secrets-master\app.js:57:14)

**Comment by pandeyom331** [comment]
.
